services:
  rethinkdb:
    restart: unless-stopped
    container_name: rethinkdb
    image: rethinkdb:latest
    ports:
      - "8089:8080"
      - "28015:28015"
      - "29015:29015"
    command: rethinkdb --bind all --http-port 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./rethinkdb:/data
    networks:
      - default

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default

  api:
    restart: unless-stopped
    container_name: api
    working_dir: /var/www/html
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xRwtjABrXzT0dz5c1SJRtKeINt/ThhB2vx2bvPhgL64=
      - DB_CONNECTION=rethinkdb
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - DB_DATABASE=laravel
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    ports:
      - "9000:9000"
    depends_on:
      rethinkdb:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    networks:
      - default

  web:
    restart: unless-stopped
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    networks:
      - default

networks:
  default:
    driver: bridge
