services:
  api:
    restart: unless-stopped
    container_name: api
    working_dir: /var/www/html
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xRwtjABrXzT0dz5c1SJRtKeINt/ThhB2vx2bvPhgL64=
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - DB_DATABASE=palm_outsourcing
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    ports:
      - "9000:9000"
    depends_on:
      rethinkdb:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  rethinkdb:
    image: rethinkdb:latest
    ports:
      - "28015:28015"
      - "29015:29015"
      - "8089:8080"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
        - NEXT_PUBLIC_API_URL=http://webserver:80
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
      webserver:
        condition: service_healthy
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://webserver:80
    networks:
      - default

networks:
  default:
